### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ArtMaZa**
add header on desktop and mobile

### CODE REVIEW

**Comment by mhryshkin** [comment]
@ArtMaZa To follow GitFlow conventions let's don't merge something into 'master' directly but merge in 'dev' instead, could you please create a branch from the 'dev' with a meaningful name and recreate the PR?

**Comment by ArtMaZa** [comment]
So I must somehow cancel this PR?

**Comment by mhryshkin** [comment]
Yes, you have to close this PR, there is a button which does it



> So I must somehow cancel this PR?
Yeas

**Comment by ArtMaZa** [comment]
button "Close with comment"? 
> Yes, you have to close this PR, there is a button which does it
> 
> > So I must somehow cancel this PR?
And next commits I should do in a branch from dev and make PR to merge in dev?

**Comment by ArtMaZa** [comment]
button "Close with comment"?
And next commits I should do in a branch from dev and make PR to merge in dev?
> Yes, you have to close this PR, there is a button which does it
> 
> > So I must somehow cancel this PR?

**Comment by ArtMaZa** [comment]
Should I change assignees every time when I write comment?

**Comment by mhryshkin** [comment]
> button "Close with comment"?
> And next commits I should do in a branch from dev and make PR to merge in dev?
> 
> > Yes, you have to close this PR, there is a button which does it
> > > So I must somehow cancel this PR?

This button:
image

Yes, we will merge into 'master' only once the whole page is done, in the meantime, we will use only the 'dev' branch. Actually, it's not necessary to close this PR, you can create a new branch from master and call it 'dev', then rename the current branch to something like 'feature/{feature-name}' to follow GitFlow conventions and change the destination of the current PR to 'dev'

**Comment by mhryshkin** [comment]
> Should I change assignees every time when I write comment?

It's not necessary :)

**Comment by ArtMaZa** [comment]
Oh, it's clear. Can I change name branches on github or just on my local PC?

**Comment by mhryshkin** [comment]
> Oh, it's clear. Can I change name branches on github or just on my local PC?

There is no clear way to rename a remote branch, so it seems like you will have to close this PR :)

**Comment by ArtMaZa** [comment]
Ok, will see on next PR)

**Pull request closed without merging**
